### ISSUE TITLE
Real management service component

### ISSUE THREAD

**Issue by morphis** [01org/wds#120]
What is the actual prupose of the WDS project? Is it just to have a library bundling the core of WiFi Display or to implement also a management service component on top of that plugging all bits and peaces together (like the desktop_source_test/sink_test utilities are already doing to some degree)?

**Comment by kanavin** [comment]
It's a library + sample applications. We're not doing management component anything, because it requires integration into a specific system for audio/video playback and determining screen parameters and writing a management UI and such. Our goal is to be agnostic of any specific media pipelines, ui toolkits and rtp streaming solutions.

**Comment by morphis** [comment]
Thanks for the comment on this.
